In [1]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
sentences = [
    "I love AI",
    "Deep Learning is amazing",
    "I hate bugs",
    "Python is awesome",
    "Machine Learning is powerful",
    "I dislike errors"
]

labels = [1, 1, 0, 1, 1, 0]

In [3]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[1, 4, 5], [6, 3, 2, 7], [1, 8, 9], [10, 2, 11], [12, 3, 2, 13], [1, 14, 15]]


In [4]:
max_length = 5

X = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post"
)

y = np.array(labels)

print(X)
print(y)

[[ 1  4  5  0  0]
 [ 6  3  2  7  0]
 [ 1  8  9  0  0]
 [10  2 11  0  0]
 [12  3  2 13  0]
 [ 1 14 15  0  0]]
[1 1 0 1 1 0]


In [5]:
vocab_size = len(tokenizer.word_index) + 1

print(vocab_size)

16


# Build the LSTM Model

In [6]:
model = tf.keras.Sequential([

    tf.keras.layers.Embedding(
        input_dim=vocab_size,
        output_dim=32,
        input_length=max_length
    ),

    tf.keras.layers.LSTM(
        units=64
    ),

    tf.keras.layers.Dense(
        1,
        activation="sigmoid"
    )

])

C:\Users\subha\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [9]:
history = model.fit(
    X,
    y,
    epochs=20,
    batch_size=2
)

Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.6902
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6835
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6792
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6727
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6628
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.6539
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.6430
Epoch 9/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6667 - loss: 0.6242    
Epoch 10/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6667 - loss: 0.6047
Epoch 11/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6667 - loss: 0.5829
Epoch 12/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.539

In [10]:
loss, accuracy = model.evaluate(X, y)

print("Loss:", loss)
print("Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 1.0000 - loss: 0.1115
Loss: 0.11150767654180527
Accuracy: 1.0


In [11]:
test = ["I love Machine Learning"]

test_seq = tokenizer.texts_to_sequences(test)

test_pad = pad_sequences(
    test_seq,
    maxlen=max_length,
    padding="post"
)

prediction = model.predict(test_pad)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step
[[0.95169455]]


In [12]:
if prediction[0][0] > 0.5:
    print("Positive")
else:
    print("Negative")

Positive


# Understanding the LSTM Layer